### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by elcolie** [elcolie/HT6MInterface#3]
1 scenario has multiple heat source

**Comment by awatarn** [comment]
ใช่แล้ว 1 scenario สามารถมี heat source ได้หลายแบบ ในแต่ละช่วงเวลา
คล้ายๆกับการให้กำลังไฟและวิธีการที่แต่ละเวลาต่างกัน บางช่วงใช้เป็น microwave (ICRF) อย่างเดียว บางช่วงเป็นการยิงอนุภาค (NBI)
