### ISSUE TITLE
Step5: How to validate `time at this break point`?

### ISSUE THREAD

**Issue by elcolie** [elcolie/HT6MInterface#4]
How to validate `time at this break point`?

**Comment by awatarn** [comment]
Step 4/5 ผู้ใช้กรอก number of break points (no_break_points) และ  t_max เข้ามา
เช่น no_break_points = 5, t_max = 4
break point อันดับแรกให้เป็นเวลาที่ t=0 และสุดท้าย เป็นเวลาที่ t=t_max เปลี่ยนแปลงไม่ได้
ส่วน 3 break points ที่เหลือ วิธีการคำนวณเวลาของแต่ละจุดนี้ให้เวลาแต่ละช่วงห่างเท่าๆกัน หรือคิดได้ตามสูตรนี้
time_break_point(0) = 0
time_break_point(1) = 1
time_break_point(2) = 2
time_break_point(3) = 3
.
.
.
time_break_point( i ) = t_max*i/(no_break_point - 1)
.
.
.
time_break_point(no_break_points - 1) = time_break_point(4) = t_max = 4

เมื่อมาถึง step 5/5 เวลาของแต่ละ break point จะมีค่าตาม default ที่ได้คำนวณก่อนหน้านี้อยู่แล้ว แต่ว่าผู้ใช้สามารถเปลี่ยนแปลงได้เองด้วย [ยกเว้นตัวแรก i  = 0 และตัวสุดท้าย i = no_break_points - 1 ห้ามเปลี่ยนแปลงค่า] โดยที่มีเงื่อนไขว่า  time_break_point( i-1 ) < time_break_point( i ) เสมอ (เวลาของ break point ก่อนหน้า ต้องมีค่าน้อยกว่าตัวถัดไป)

**Comment by elcolie** [comment]
> ส่วน 3 break points ที่เหลือ วิธีการคำนวณเวลาของแต่ละจุดนี้ให้เวลาแต่ละช่วงห่างเท่าๆกัน หรือคิดได้ตามสูตรนี้

แปลว่ามีค่า default ให้แต่จะกรอกเองก็ได้ถูกไหม?

**Comment by awatarn** [comment]
ใช่แล้ว ให้เป็น default เอาไว้ แต่เปลี่ยนได้ ซึ่งถ้ามีการเปลี่ยนแปลงค่า ค่าใหม่ต้องสอดคล้องกับเงื่อนไขว่า time_break_point( i-1 ) < time_break_point( i ) เสมอ
